blank_issues_enabled: false
contact_links:
  - name: Have a general question?
    url: https://github.com/OMEGARAZER/bulk-downloader-for-reddit-x/discussions
    about: Have questions about BDFRx, ask anything you like on the discussions board
