name: Security

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"

jobs:
  Safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip safety setuptools
          pip install .[dev]
      - name: Execute safety
        run: safety check
