name: Python Test

on:
  push:
    paths-ignore:
      - "**.md"
      - ".markdownlint.json"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "scripts/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".markdownlint.json"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "scripts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
        ext: [.sh]
        include:
        - os: windows-latest
          python-version: 3.9
          ext: .ps1
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade black pip pytest pytest-cov ruff
        pip install .

    - name: Make configuration for tests
      env:
        REDDIT_TOKEN: ${{ secrets.REDDIT_TEST_TOKEN }}
      run: |
        ./devscripts/configure${{ matrix.ext }}

    - name: Black formatting check
      run: |
        black --check bdfrx tests scripts/*.py

    - name: Critical ruff lint
      run: |
        ruff check --format=github --select=E9,F63,F7,F82,I .

    - name: Full ruff lint
      run: |
        ruff check --format=github . --exit-zero

    - name: Test with pytest
      run: |
        pytest -m "not slow" --verbose --cov=./bdfrx/ --cov-report term:skip-covered --cov-report html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage_report
        path: htmlcov/
